#ifndef __VESC_INST_H
#define __VESC_INST_H

#define VESC_SET_DUTY 0
#define VESC_SET_CURRENT 1
#define VESC_SET_CURRENT_BRAKE 2
#define VESC_SET_RPM 3
#define VESC_SET_POS 4
#define VESC_SET_CURRENT_REL 10
#define VESC_SET_BRAKE_REL 11
#define VESC_SET_CURRENT_HANDBRAKE 12
#define VESC_SET_CURRENT_HANDBRAKE_REL 13

#define VESC_STATUS 9
#define VESC_STATUS_2 14
#define VESC_STATUS_3 15
#define VESC_STATUS_4 16
#define VESC_STATUS_5 27
#define VESC_STATUS_6 28

#endif